// src/components/ImgText.tsx
interface ImgTextProps {
  image?: string
  imageAlt?: string
  className?: string
  style?: React.CSSProperties
  children: React.ReactNode
}

const ImgText = ({ image, imageAlt = "", className = "", style, children }: ImgTextProps) => {
  return (
    <div className={`ImgText ${className}`} style={style}>
        {image && <figure><img src={image} alt={imageAlt}/></figure>}
        <div>
        {children}
        </div>
    </div>
  )
}

export { ImgText }

// src/components/ImgText.vue
<script setup lang="ts">
interface ImgTextProps {
  image?: string
  class?: string
  style?: Record<string, string>
}

defineSlots<{
  default?: () => any
}>()

const props = defineProps<ImgTextProps>()
</script>

<template>
  <div :class="`ImgText ${props.class || ''}`" :style="props.style">
    <figure v-if="image"><img :src="image" alt=""/></figure>
    <div class="">
      <slot />
    </div>
  </div>
</template>
